import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { DesktopLayout } from "../../components";

export default function Home() {
  return (
    <DesktopLayout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Med-X Desktop!</a>
          </h1>
        </main>
      </div>
    </DesktopLayout>
  );
}
